
[package]
name = "leptos_studio"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.6"
leptos_router = "0.6"
leptos_dom = "0.6"
web-sys = { version = "0.3", features = ["DragEvent", "DataTransfer", "Window", "Storage", "console", "HtmlInputElement", "FileList", "File", "Clipboard", "Navigator"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console_error_panic_hook = "0.1"
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
gloo-timers = { version = "0.3.0", features = ["futures"] }
wasm-bindgen-futures = "0.4.50"
gloo-net = "0.6.0"

[workspace]
# (tidak ada members, single crate)

[workspace.metadata.dylint]
libraries = [{ git = "https://github.com/leptos-rs/leptos-lints", tag = "v0.1.0" }]

[profile.release]
lto = true
codegen-units = 1
